version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: sq_user
      POSTGRES_PASSWORD: sq_password
      POSTGRES_DB: swiftqueue
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_DB_DRIVER: server

volumes:
  postgres_data:
